name: Test R Setup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *'

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfreetype6-dev libfontconfig1-dev libharfbuzz-dev \
            libfribidi-dev libcurl4-openssl-dev libssl-dev \
            libxml2-dev libpng-dev libtiff5-dev libnetcdf-dev

      - name: Install R packages
        run: |
          CDI_DOMAIN=template Rscript scripts/cdi-install-packages.R
